os: "linux" # possible values: linux, windows
setup_folders: False # boolean (True or False)
output_folder: "output"
datasets_folder: "Datasets"
resources_folder: "resources"
dataset: "small" # possible values: small, latest
filenames: ["links", "movies", "ratings", "tags", "test_recommendation"]
dataset-file-extention: ".csv"
execution_kind: "normal" # possible values: normal, test
methods: ["collaborative"]
models:
  collaborative: ["pearson"]
  content-based: ["knn", "rf", "dnn"]
embeddings_file: "glove.6B.50d.txt"
embeddings_zip_file: "glove.6B.zip"
embeddings_file_url: "http://nlp.stanford.edu/data/glove.6B.zip"
aggregation: "avg" # possible values: avg, max
classification: "binary" # possible values: binary, multi ==> multi == classes 1-5
cross-validation: 10 # k-folds for training the models
metric_best_model: "micro_f" # Possible values: "macro-precision", "micro-precision", "macro-recall", "micro-recall", "macro-f", "micro-f"
knn:
  neighbors: 30 # KNN neighbors
rf:
  estimators: 500
  max_depth: 10
dnn:
  hidden_layers: [[1000, "relu", 0.5], [500, "relu", 0.5], ["softmax"]] # first number is hidden units, second one is the activation function and third one is the dropout
  sgd:
    lr: 0.01
    decay: 0.000001
    momentum: 0.9
    nesterov: True
  loss: "categorical_crossentropy" # possible values are binary_crossentropy and categorical_crossentropy
  metrics: ["accuracy"]
  epochs: 100
  batch_size: 500
kmeans:
  clusters: 10
  n_init: 20
  max_iter: 500
  n_similar: 30
qualitative:
  threshold: 10
  top_num: 20
email:
  user: "user@gmail.com"
  password: "qwerty"
